<?php

namespace ContainerMdMITyJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FTBXF3wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fTBXF3w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fTBXF3w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'developerRepository' => ['privates', 'App\\Repository\\DeveloperRepository', 'getDeveloperRepositoryService', true],
        ], [
            'developerRepository' => 'App\\Repository\\DeveloperRepository',
        ]);
    }
}
