<?php

namespace ContainerMdMITyJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OZpD0b8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OZpD0b8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OZpD0b8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'editor' => ['privates', '.errored..service_locator.OZpD0b8.App\\Entity\\Editor', NULL, 'Cannot autowire service ".service_locator.OZpD0b8": it references class "App\\Entity\\Editor" but no such service exists.'],
        ], [
            'editor' => 'App\\Entity\\Editor',
        ]);
    }
}
