<?php

namespace ContainerMdMITyJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PJncMuEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pJncMuE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pJncMuE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'editorRepository' => ['privates', 'App\\Repository\\EditorRepository', 'getEditorRepositoryService', true],
        ], [
            'editorRepository' => 'App\\Repository\\EditorRepository',
        ]);
    }
}
