<?php

namespace ContainerMdMITyJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeveloperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ys.wb.a.App\Entity\Developer' shared service.
     *
     * @return \App\Entity\Developer
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ys.wb.a": it references class "App\\Entity\\Developer" but no such service exists.');
    }
}
