<?php

namespace ContainerMdMITyJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OZpD0b8.App\Entity\Editor' shared service.
     *
     * @return \App\Entity\Editor
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OZpD0b8": it references class "App\\Entity\\Editor" but no such service exists.');
    }
}
