<?php

namespace ContainerMdMITyJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditorTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\EditorType' shared autowired service.
     *
     * @return \App\Form\EditorType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/EditorType.php';

        return $container->privates['App\\Form\\EditorType'] = new \App\Form\EditorType();
    }
}
